/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MetodosDeCreacionLogica;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    
    MetodosDeCreacionLogica mcl;
    String tipoAutomata;
    
    public Frame() {
        initComponents();
        mcl=new MetodosDeCreacionLogica();
        tipoAutomata="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new vista.Panel();
        jLabel1 = new javax.swing.JLabel();
        jblAfd = new javax.swing.JLabel();
        cbAfd = new javax.swing.JCheckBox();
        jblAfn = new javax.swing.JLabel();
        cbAfnd = new javax.swing.JCheckBox();
        jblAfnd_e = new javax.swing.JLabel();
        cbAfne = new javax.swing.JCheckBox();
        jblQ = new javax.swing.JLabel();
        txtEstados = new javax.swing.JTextField();
        jblLenguaje = new javax.swing.JLabel();
        txtLenguaje = new javax.swing.JTextField();
        jblQ0 = new javax.swing.JLabel();
        txtEstadoInicial = new javax.swing.JTextField();
        jblNombreAutomata = new javax.swing.JLabel();
        txtNombreAutomata = new javax.swing.JTextField();
        btnCrearAutomata = new javax.swing.JButton();
        jblCrearTransiciones = new javax.swing.JLabel();
        jblTransicionInicial = new javax.swing.JLabel();
        txtTransicionInicial = new javax.swing.JTextField();
        jblSimbolo = new javax.swing.JLabel();
        txtSimbolosTransicion = new javax.swing.JTextField();
        jblTransicionFinal = new javax.swing.JLabel();
        txtTransicionFinal = new javax.swing.JTextField();
        jblSeleccionarAutomata = new javax.swing.JLabel();
        cbSeleccionarAutomata = new javax.swing.JComboBox();
        btnCrearTransicion = new javax.swing.JButton();
        jblQuintupla = new javax.swing.JLabel();
        cbQuintupla = new javax.swing.JComboBox();
        btnMostrarQuintupla = new javax.swing.JToggleButton();
        jblEstadosQuintupla = new javax.swing.JLabel();
        txtEstadosQuintupla = new javax.swing.JTextField();
        jblLenguajeQuintupla = new javax.swing.JLabel();
        txtLenguajeQuintupla = new javax.swing.JTextField();
        jblEstadoInicialQuintupla = new javax.swing.JLabel();
        txtEstadoInicialQuintupla = new javax.swing.JTextField();
        jblEstadoAceptadorQuintupla = new javax.swing.JLabel();
        btnMostrarTabla = new javax.swing.JButton();
        btnSeleccionarAutomataTabla = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jblEstadosAceptadores = new javax.swing.JLabel();
        txtEstadosAceptadores = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel1.setText("PROYECTO AUTOMATAS");

        jblAfd.setText("ADF");

        cbAfd.setText("?");
        cbAfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAfdActionPerformed(evt);
            }
        });

        jblAfn.setText("AFND");

        cbAfnd.setText("?");
        cbAfnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAfndActionPerformed(evt);
            }
        });

        jblAfnd_e.setText("AFND-E");

        cbAfne.setText("?");
        cbAfne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAfneActionPerformed(evt);
            }
        });

        jblQ.setText("Q");

        txtEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadosActionPerformed(evt);
            }
        });

        jblLenguaje.setText("Σ");

        txtLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLenguajeActionPerformed(evt);
            }
        });

        jblQ0.setText("Q0");

        txtEstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoInicialActionPerformed(evt);
            }
        });

        jblNombreAutomata.setText("NOMBRE AUTOMATA");

        txtNombreAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAutomataActionPerformed(evt);
            }
        });

        btnCrearAutomata.setText("CREAR AUTOMATA");
        btnCrearAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAutomataActionPerformed(evt);
            }
        });

        jblCrearTransiciones.setText("CREAR TRANSICIONES");

        jblTransicionInicial.setText("QA");

        jblSimbolo.setText("SIMBOLO_Σ");

        jblTransicionFinal.setText("QB");

        txtTransicionFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransicionFinalActionPerformed(evt);
            }
        });

        jblSeleccionarAutomata.setText("SELECCINAR AUTOMATA");

        cbSeleccionarAutomata.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSeleccionarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarAutomataActionPerformed(evt);
            }
        });

        btnCrearTransicion.setText("CREAR TRANSICION");
        btnCrearTransicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTransicionActionPerformed(evt);
            }
        });

        jblQuintupla.setText("QUINTUPLA DE AUTOMATA");

        cbQuintupla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbQuintupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuintuplaActionPerformed(evt);
            }
        });

        btnMostrarQuintupla.setText("MOSTRAR QUINTUPLA");

        jblEstadosQuintupla.setText("Q");

        txtEstadosQuintupla.setEditable(false);

        jblLenguajeQuintupla.setText("Σ");

        txtLenguajeQuintupla.setEditable(false);
        txtLenguajeQuintupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLenguajeQuintuplaActionPerformed(evt);
            }
        });

        jblEstadoInicialQuintupla.setText("Q0");

        txtEstadoInicialQuintupla.setEditable(false);

        jblEstadoAceptadorQuintupla.setText("F");

        btnMostrarTabla.setText("Mostrar Tabla");

        btnSeleccionarAutomataTabla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        btnSeleccionarAutomataTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarAutomataTablaActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jButton4.setText("Verificar Cadena");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jButton5.setText("Complemento");

        jButton6.setText("Union");

        jButton7.setText("Interseccion");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton8.setText("Reversa");

        jButton9.setText("Minimizar");

        jblEstadosAceptadores.setText("f");

        txtEstadosAceptadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadosAceptadoresActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jblEstadosQuintupla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstadosQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblLenguajeQuintupla)
                        .addGap(18, 18, 18)
                        .addComponent(txtLenguajeQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblEstadoInicialQuintupla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstadoInicialQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblEstadoAceptadorQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarTabla)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarAutomataTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jblTransicionInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTransicionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblQuintupla)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(btnMostrarQuintupla))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jblSimbolo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSimbolosTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jblTransicionFinal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTransicionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblSeleccionarAutomata)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSeleccionarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCrearTransicion))))
                            .addComponent(cbQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jblCrearTransiciones)
                                        .addGap(67, 67, 67))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jblAfd)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAfd)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblAfn)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAfnd)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblAfnd_e)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAfne)
                                        .addGap(41, 41, 41)))
                                .addComponent(jblQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel1))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jblLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jblQ0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jblEstadosAceptadores, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstadosAceptadores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(jblNombreAutomata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearAutomata)))
                        .addGap(0, 133, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(450, 450, 450))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblAfd)
                    .addComponent(cbAfd)
                    .addComponent(jblQ)
                    .addComponent(txtEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblLenguaje)
                    .addComponent(txtLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAutomata)
                    .addComponent(jblEstadosAceptadores)
                    .addComponent(txtEstadosAceptadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblAfn)
                    .addComponent(cbAfnd)
                    .addComponent(jblQ0)
                    .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreAutomata)
                    .addComponent(txtNombreAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblAfnd_e)
                    .addComponent(cbAfne))
                .addGap(18, 22, Short.MAX_VALUE)
                .addComponent(jblCrearTransiciones)
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblTransicionInicial)
                    .addComponent(txtTransicionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTransicionFinal)
                    .addComponent(txtTransicionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblSeleccionarAutomata)
                    .addComponent(jblSimbolo)
                    .addComponent(txtSimbolosTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSeleccionarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearTransicion))
                .addGap(18, 18, 18)
                .addComponent(jblQuintupla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarQuintupla))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadosQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblEstadosQuintupla)
                    .addComponent(txtLenguajeQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblLenguajeQuintupla)
                    .addComponent(txtEstadoInicialQuintupla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblEstadoInicialQuintupla)
                    .addComponent(jblEstadoAceptadorQuintupla)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTabla)
                    .addComponent(btnSeleccionarAutomataTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAutomataActionPerformed

        
        if (tipoAutomata!="") 
        {
            
            if (tipoAutomata.equals("AFD")) 
            {
                mcl.crearAutomaatAFD_O_AFN(txtNombreAutomata.getText(), tipoAutomata,txtEstados.getText(), txtLenguaje.getText(), txtEstadoInicial.getText(),txtEstadosAceptadores.getText());
                JOptionPane.showMessageDialog(new Frame(),"Se creo el automata Exitosamente \n Ya puede agregar transiciones");
                System.out.println(""+mcl.getAutomatas().size());
            }
            
            if(tipoAutomata.equals("AFND"))
            {
                mcl.crearAutomaatAFD_O_AFN(txtNombreAutomata.getText(), tipoAutomata,txtEstados.getText(), txtLenguaje.getText(), txtEstadoInicial.getText(),txtEstadosAceptadores.getText());
                JOptionPane.showMessageDialog(new Frame(),"Se creo el automata Exitosamente \n Ya puede agregar transiciones");
                System.out.println(""+mcl.getAutomatas().size());
            }
            
            if (tipoAutomata.equals("AFND_E")) 
            {
                mcl.crearAutomaatAFN_E(txtNombreAutomata.getText(), tipoAutomata,txtEstados.getText(), txtLenguaje.getText(), txtEstadoInicial.getText(),txtEstadosAceptadores.getText());
                JOptionPane.showMessageDialog(new Frame(),"Se creo el automata Exitosamente \n Ya puede agregar transiciones E");
                System.out.println(""+mcl.getAutomatas().size());
            }
            cbSeleccionarAutomata.removeAllItems();
            cbQuintupla.removeAllItems();
            btnSeleccionarAutomataTabla.removeAllItems();
            jComboBox8.removeAllItems();
            for (int i = 0; i < mcl.getAutomatas().size(); i++) 
            {
                cbSeleccionarAutomata.addItem(""+mcl.getAutomatas().get(i).getNombre());
                btnSeleccionarAutomataTabla.addItem(""+mcl.getAutomatas().get(i).getNombre());
                cbQuintupla.addItem(""+mcl.getAutomatas().get(i).getNombre());
                jComboBox8.addItem(""+mcl.getAutomatas().get(i).getNombre());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(new Frame(),"Seleccione tipo de Automata");
        }
 
    }//GEN-LAST:event_btnCrearAutomataActionPerformed

    
    
    private void cbAfneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAfneActionPerformed
         if(cbAfd.isSelected()==true)
        {
            cbAfd.setSelected(false);
        }
        if(cbAfnd.isSelected()==true)
        {
            cbAfnd.setSelected(false);
        }
        
        tipoAutomata="AFND_E";
    }//GEN-LAST:event_cbAfneActionPerformed

    
    
    
    private void txtTransicionFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransicionFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransicionFinalActionPerformed

    private void txtLenguajeQuintuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLenguajeQuintuplaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLenguajeQuintuplaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    
    
    private void cbAfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAfdActionPerformed
        if(cbAfne.isSelected()==true)
        {
            cbAfne.setSelected(false);
        }
        if(cbAfnd.isSelected()==true)
        {
            cbAfnd.setSelected(false);
        }
        
        tipoAutomata="AFD";
        
    }//GEN-LAST:event_cbAfdActionPerformed

    
    
    
    private void cbAfndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAfndActionPerformed
        
        if(cbAfne.isSelected()==true)
        {
            cbAfne.setSelected(false);
        }
        if(cbAfd.isSelected()==true)
        {
            cbAfd.setSelected(false);
        }
        
        tipoAutomata="AFND";
    }//GEN-LAST:event_cbAfndActionPerformed

    
    
    
    
    private void txtEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadosActionPerformed

    private void txtLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLenguajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLenguajeActionPerformed

    private void txtEstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoInicialActionPerformed

    private void txtEstadosAceptadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadosAceptadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadosAceptadoresActionPerformed

    private void txtNombreAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAutomataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutomataActionPerformed

    private void cbSeleccionarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarAutomataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeleccionarAutomataActionPerformed

    private void cbQuintuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuintuplaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuintuplaActionPerformed

    private void btnSeleccionarAutomataTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarAutomataTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarAutomataTablaActionPerformed

    private void btnCrearTransicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTransicionActionPerformed
        
        String tipoAutomataTransicion="";
        for (int i = 0; i < mcl.getAutomatas().size(); i++) {
            if (mcl.getAutomatas().get(i).getNombre().equals(cbSeleccionarAutomata.getSelectedItem())) {
                tipoAutomataTransicion=mcl.getAutomatas().get(i).getTipoAutomata();
            }
        }
        
        if (!tipoAutomataTransicion.equals("")) 
        {
            System.out.println(""+cbSeleccionarAutomata.getSelectedItem());
            if (tipoAutomataTransicion.equals("AFD")) 
            {
                mcl.agregarTransicionAFD(cbSeleccionarAutomata.getSelectedItem()+"", txtTransicionInicial.getText(), txtSimbolosTransicion.getText(), txtTransicionFinal.getText());
            }
            else
            {
                mcl.agregarTransicionAFN_O_AFNE(cbSeleccionarAutomata.getSelectedItem()+"", txtTransicionInicial.getText(), txtSimbolosTransicion.getText(), txtTransicionFinal.getText());
            }
        }
        
        
        
    }//GEN-LAST:event_btnCrearTransicionActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
       jTextField12.setText( ""+mcl.lectorDeCadena(jComboBox8.getSelectedItem()+"",jTextField11.getText()+""));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        
    }//GEN-LAST:event_jTextField12ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAutomata;
    private javax.swing.JButton btnCrearTransicion;
    private javax.swing.JToggleButton btnMostrarQuintupla;
    private javax.swing.JButton btnMostrarTabla;
    private javax.swing.JComboBox btnSeleccionarAutomataTabla;
    private javax.swing.JCheckBox cbAfd;
    private javax.swing.JCheckBox cbAfnd;
    private javax.swing.JCheckBox cbAfne;
    private javax.swing.JComboBox cbQuintupla;
    private javax.swing.JComboBox cbSeleccionarAutomata;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JLabel jblAfd;
    private javax.swing.JLabel jblAfn;
    private javax.swing.JLabel jblAfnd_e;
    private javax.swing.JLabel jblCrearTransiciones;
    private javax.swing.JLabel jblEstadoAceptadorQuintupla;
    private javax.swing.JLabel jblEstadoInicialQuintupla;
    private javax.swing.JLabel jblEstadosAceptadores;
    private javax.swing.JLabel jblEstadosQuintupla;
    private javax.swing.JLabel jblLenguaje;
    private javax.swing.JLabel jblLenguajeQuintupla;
    private javax.swing.JLabel jblNombreAutomata;
    private javax.swing.JLabel jblQ;
    private javax.swing.JLabel jblQ0;
    private javax.swing.JLabel jblQuintupla;
    private javax.swing.JLabel jblSeleccionarAutomata;
    private javax.swing.JLabel jblSimbolo;
    private javax.swing.JLabel jblTransicionFinal;
    private javax.swing.JLabel jblTransicionInicial;
    private vista.Panel panel1;
    private javax.swing.JTextField txtEstadoInicial;
    private javax.swing.JTextField txtEstadoInicialQuintupla;
    private javax.swing.JTextField txtEstados;
    private javax.swing.JTextField txtEstadosAceptadores;
    private javax.swing.JTextField txtEstadosQuintupla;
    private javax.swing.JTextField txtLenguaje;
    private javax.swing.JTextField txtLenguajeQuintupla;
    private javax.swing.JTextField txtNombreAutomata;
    private javax.swing.JTextField txtSimbolosTransicion;
    private javax.swing.JTextField txtTransicionFinal;
    private javax.swing.JTextField txtTransicionInicial;
    // End of variables declaration//GEN-END:variables
}
